targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/domain/**/models/**.dart
          - lib/data/**/dtos/**.dart
          - lib/presentation/**/bloc/**state.dart
          - lib/presentation/bloc/**.dart
      json_serializable:
        generate_for:
          - lib/data/**/dtos/**.dart
      injectable_generator:injectable_builder:
        generate_for:
          - lib/data/**.dart
          - lib/domain/**.dart
          - lib/presentation/**.dart
      injectable_generator:injectable_config_builder:
        generate_for:
          - lib/core/services/injection.dart
