name: fastdo
description: "A one-tap Quick Settings toggle for Android Developer Options."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # State Management & Architecture
  flutter_bloc: ^9.1.1
  fpdart: ^1.1.0
  get_it: ^9.3.0
  injectable: ^3.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  go_router: ^18.0.2

  # Icons
  cupertino_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  freezed: ^4.0.2
  injectable_generator: ^3.1.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
